/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.shark.aplikasipustaka;

/**
 *
 * @author ogy
 */

import Controller.KelolaPustaka;
import com.shark.aplikasipustaka.MenuUtama;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

public class DataPustaka extends javax.swing.JFrame {

    //Variabel Global
    private final DefaultTableModel model;
    private ResultSet res;
    private String search, judul, jenis, penerbit, tahun, pengarang, key, action;
    
    /**
     * Creates new form DataPustaka
     */
    public DataPustaka() {
        initComponents();
        
        // instansiasi class tabel kedalam variabel model
        model = new DefaultTableModel();
            //membuat tabel head
            jTablePustaka.setModel(model);
            model.addColumn("No");
            model.addColumn("Id");
            model.addColumn("Judul");
            model.addColumn("Jenis");
            model.addColumn("Penerbit");
            model.addColumn("Tahun");
            model.addColumn("Pengarang");
            
            settingColumn();
            lihatPustaka();   
            lihatPengarang();
            
    }
    
    public void settingColumn(){
        
        TableColumn column;
        
        jTablePustaka.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        column = jTablePustaka.getColumnModel().getColumn(0);
        column.setPreferredWidth(30);
        column = jTablePustaka.getColumnModel().getColumn(1);
        column.setPreferredWidth(30);
        column = jTablePustaka.getColumnModel().getColumn(2);
        column.setPreferredWidth(250);
        column = jTablePustaka.getColumnModel().getColumn(3);
        column.setPreferredWidth(100);
        column = jTablePustaka.getColumnModel().getColumn(4);
        column.setPreferredWidth(200);
        column = jTablePustaka.getColumnModel().getColumn(5);
        column.setPreferredWidth(100);
        column = jTablePustaka.getColumnModel().getColumn(6);
        column.setPreferredWidth(200);
    }
    
    private void lihatPustaka(){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        try{
            search = jSearch.getText();
            res = KelolaPustaka.melihatPustaka(search);
            
            int x = 1;
            
            while(res.next() ){
                Object[] obj = new Object[7];
                obj[0] = x;
                obj[1] = res.getString("id");
                obj[2] = res.getString("judul");
                obj[3] = res.getString("jenis");
                obj[4] = res.getString("penerbit");
                obj[5] = res.getString("tahun");
                obj[6] = res.getString("nm_pengarang");
                
                model.addRow(obj);
                x++;
            }
        }catch (SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage() );
        }
    }
    
    private void lihatPengarang(){
        try{            
            res = KelolaPustaka.melihatPengarang();
            
            while(res.next() ){
                Object[] list = new Object[3];
                list[0] = res.getString("nm_pengarang");
                
                jComboPengarang.addItem(list[0]);
            }
            
        }catch (SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage() );
        }
    }
    
    private void setVar(){
        judul = jTextJudul.getText();
        jenis = jTextJenis.getText();
        penerbit = jTextPenerbit.getText();
        tahun = jTextTahun.getText();
    }
    
    private void resetForm(){
        jSearch.setText(null);
        jTextJudul.setText(null);
        jTextJenis.setText(null);
        jTextPenerbit.setText(null);
        jTextTahun.setText(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePustaka = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextJudul = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextJenis = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextPenerbit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButtonSimpan = new javax.swing.JButton();
        jButtonBatal = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jComboPengarang = new javax.swing.JComboBox();
        jSearch = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextTahun = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Data Pustaka");

        jTablePustaka.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablePustaka.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePustakaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePustaka);

        jLabel2.setText("Judul Buku");

        jLabel3.setText("Jenis Buku");

        jLabel4.setText("Penerbit");

        jLabel5.setText("Pengarang");

        jButtonSimpan.setText("Simpan");
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });

        jButtonBatal.setText("Batal");

        jButtonHapus.setText("Hapus");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });

        jButtonExit.setText("Keluar");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jComboPengarang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { }));
        jComboPengarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboPengarangActionPerformed(evt);
            }
        });

        jSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchActionPerformed(evt);
            }
        });

        jLabel8.setText("Cari");

        jLabel9.setText("Tahun");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBatal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonExit))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jTextPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jTextTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jTextJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jComboPengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboPengarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSimpan)
                    .addComponent(jButtonBatal)
                    .addComponent(jButtonHapus)
                    .addComponent(jButtonExit))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchActionPerformed
        // TODO add your handling code here:
        lihatPustaka();
        resetForm();
    }//GEN-LAST:event_jSearchActionPerformed

    private void jComboPengarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboPengarangActionPerformed
        // TODO add your handling code here:
        pengarang = String.valueOf(jComboPengarang.getSelectedItem() );
        
    }//GEN-LAST:event_jComboPengarangActionPerformed

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        // TODO add your handling code here:
        action = jButtonSimpan.getText();
        if(jTextJudul.getText().equals("") ){
            JOptionPane.showMessageDialog(this,"Data Pustaka Tidak Boleh Kosong!");
        }else {
            setVar();

            if(action == "Simpan"){
                KelolaPustaka.memasukkanPustaka(judul, jenis, penerbit, tahun, pengarang);
            }else if(action == "Update"){
                KelolaPustaka.mengubahPustaka(key, judul, jenis, penerbit, tahun, pengarang);
            }else{
                JOptionPane.showMessageDialog(null,"Logika Kontrol Error!");
            }

            lihatPustaka();
            resetForm();
            jButtonSimpan.setText("Simpan");
        }
    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void jTablePustakaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePustakaMouseClicked
        // TODO add your handling code here:
        int baris = jTablePustaka.rowAtPoint(evt.getPoint() );
        
        jTextJudul.setText(jTablePustaka.getValueAt(baris, 2).toString() );
        jTextJenis.setText(jTablePustaka.getValueAt(baris, 3).toString() );
        jTextPenerbit.setText(jTablePustaka.getValueAt(baris, 4).toString() );
        jTextTahun.setText(jTablePustaka.getValueAt(baris, 5).toString() );
        jComboPengarang.setSelectedItem(jTablePustaka.getValueAt(baris, 6).toString());
        key = jTablePustaka.getValueAt(baris, 1).toString();
        jButtonSimpan.setText("Update");
    }//GEN-LAST:event_jTablePustakaMouseClicked

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        // TODO add your handling code here:
        if(jTextJudul.getText().equals("") ){
            JOptionPane.showMessageDialog(this,"Form Judul Kosong Tidak Ada Yang Dihapus!");
        }else {
            KelolaPustaka.menghapusPustaka(key);
            lihatPustaka();
            resetForm();
            jButtonSimpan.setText("Simpan");
        } 
    }//GEN-LAST:event_jButtonHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPustaka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPustaka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPustaka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPustaka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new DataPustaka().setVisible(true);
            }
        });
        
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBatal;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JComboBox jComboPengarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jSearch;
    private javax.swing.JTable jTablePustaka;
    private javax.swing.JTextField jTextJenis;
    private javax.swing.JTextField jTextJudul;
    private javax.swing.JTextField jTextPenerbit;
    private javax.swing.JTextField jTextTahun;
    // End of variables declaration//GEN-END:variables
}
